# Imports

In [1]:
import pandas as pd
import os
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)

# Configs

In [2]:
STAGE_DIR = "..\\enade_staging"
PARQUETS = [f for f in os.listdir(STAGE_DIR) if f.endswith(".parquet")]

# Unindo Parquets

In [28]:
dfs = []

for arq in PARQUETS:
    df = pd.read_parquet(os.path.join(STAGE_DIR, arq))
    dfs.append(df)

In [29]:
df_enade = pd.concat(dfs, ignore_index=True)
df_enade.shape

(2472225, 28)

# Renomeando Colunas

In [30]:
RENOMEAR = {
    "NU_ANO": "ano_enade",
    "CO_CATEGAD": "categoria_administrativa",
    "CO_MODALIDADE": "modalidade_graduacao",
    "CO_MUNIC_CURSO": "id_municipio",
    "CO_GRUPO": "id_curso",

    "ANO_FIM_EM": "ano_fim_ensino_medio",
    "ANO_IN_GRAD": "ano_ingresso_graduacao",
    "CO_TURNO_GRADUACAO": "turno_graduacao",

    "NT_GER": "nota_geral",
    "NT_FG": "nota_formacao_geral",
    "NT_CE": "nota_componentes_especifico",

    

    "TP_SEXO": "sexo",
    "NU_IDADE": "idade",

    "QE_I02": "cor_raca",
    "QE_I04": "escolaridade_pai",
    "QE_I05": "escolaridade_mae",
    "QE_I08": "renda_familiar",
    "QE_I10": "horas_trabalho",
    "QE_I15": "cotas",
    "QE_I17": "tipo_escola_ensino_medio",
    "QE_I21": "primeira_geracao",
    "QE_I25": "motivacao_curso",    
    
    "QE_I62": "avaliacao_equipamentos",
    "QE_I63": "avaliacao_ambiente",
    "CO_RS_I1": "avaliacao_dificuldade_fg",
    "CO_RS_I2": "avaliacao_dificuldade_ce"
}

In [31]:
df_enade = df_enade.rename(columns=RENOMEAR, inplace=False)
df_enade = df_enade.drop(columns=["CO_UF_CURSO", "CO_REGIAO_CURSO"], inplace=False)
df_enade.columns

Index(['ano_enade', 'categoria_administrativa', 'id_curso',
       'modalidade_graduacao', 'id_municipio', 'ano_fim_ensino_medio',
       'ano_ingresso_graduacao', 'turno_graduacao', 'nota_geral',
       'nota_formacao_geral', 'nota_componentes_especifico',
       'avaliacao_dificuldade_fg', 'avaliacao_dificuldade_ce',
       'avaliacao_equipamentos', 'avaliacao_ambiente', 'sexo', 'idade',
       'cor_raca', 'escolaridade_pai', 'escolaridade_mae', 'renda_familiar',
       'horas_trabalho', 'cotas', 'tipo_escola_ensino_medio',
       'primeira_geracao', 'motivacao_curso'],
      dtype='str')

# Reordenando Colunas

In [32]:
ordem = [
    "ano_enade",
    
    "id_curso",
    "categoria_administrativa",
    "modalidade_graduacao",
    "turno_graduacao",
    "id_municipio",

    "sexo",
    "idade",
    "cor_raca",

    "ano_fim_ensino_medio",
    "ano_ingresso_graduacao",
    "tipo_escola_ensino_medio",
    "primeira_geracao",
    "escolaridade_pai",
    "escolaridade_mae",
    "motivacao_curso",
    "renda_familiar",
    "horas_trabalho",
    "cotas",

    "nota_geral",
    "nota_formacao_geral",
    "nota_componentes_especifico",

    "avaliacao_dificuldade_fg",
    "avaliacao_dificuldade_ce",
    "avaliacao_equipamentos",
    "avaliacao_ambiente"

    
]

In [33]:
df_enade = df_enade[ordem]
df_enade.head()

,ano_enade,id_curso,categoria_administrativa,modalidade_graduacao,turno_graduacao,id_municipio,sexo,idade,cor_raca,ano_fim_ensino_medio,ano_ingresso_graduacao,tipo_escola_ensino_medio,primeira_geracao,escolaridade_pai,escolaridade_mae,motivacao_curso,renda_familiar,horas_trabalho,cotas,nota_geral,nota_formacao_geral,nota_componentes_especifico,avaliacao_dificuldade_fg,avaliacao_dificuldade_ce,avaliacao_equipamentos,avaliacao_ambiente
0,2018,2,1,1,4.0,5103403,F,4.0,A,1000.0,2014.0,A,A,A,A,A,A,A,A,0.0,0.0,0.0,C,C,1.0,1.0
1,2018,2,1,1,4.0,5103403,F,5.0,A,1012.0,2013.0,A,A,A,A,A,A,A,A,0.0,0.0,0.0,NaN,NaN,1.0,1.0
2,2018,2,1,1,1.0,5103403,F,11.0,A,1012.0,2013.0,A,A,A,A,A,A,A,A,0.0,0.0,0.0,NaN,NaN,1.0,1.0
3,2018,2,1,1,4.0,5103403,F,12.0,A,1013.0,2014.0,A,A,A,A,A,A,A,A,0.0,0.0,0.0,NaN,NaN,1.0,1.0
4,2018,2,1,1,4.0,5103403,F,14.0,A,1013.0,2015.0,A,A,A,A,A,A,A,A,0.0,0.0,0.0,NaN,NaN,1.0,1.0

# Decodificação de Respostas //Mapping

In [34]:
map_sexo = {
    "M": "M",
    "F": "F",
    "9": "Indefinido"
}





map_categoria_administrativa = {1: "Pública Federal",
                                  2: "Pública Estadual",
                                  3: "Pública Municipal",
                                  4: "Privada com fins lucrativos",
                                  5: "Privada sem fins lucrativos",
                                  7: "Especial"
                                  }




map_modalidade_graduacao = {0: "EAD",
                          1: "Presencial"}
map_turno_graduacao = {1.0: "Matutino",
                        2.0: "Vespertino",
                        3.0: "Integral",
                        4.0: "Noturno"}


df_enade["idade"] = df_enade["idade"].astype("Int64")
df_enade.loc[df_enade["idade"] < 15, "idade"] = pd.NA

map_cor_raca = {
    "A": "Branca",
    "B": "Preta",
    "C": "Amarela",
    "D": "Parda",
    "E": "Indígena",
    "F": "Não quero declarar"
}
df_enade['ano_fim_ensino_medio'] = df_enade['ano_fim_ensino_medio'].astype("Int64")

df_enade.loc[df_enade["ano_fim_ensino_medio"] > 2023, "ano_fim_ensino_medio"] = pd.NA

df_enade.loc[df_enade["ano_fim_ensino_medio"] < 1929, "ano_fim_ensino_medio"] = pd.NA


df_enade['ano_ingresso_graduacao'] = df_enade['ano_ingresso_graduacao'].astype("Int64")

map_tipo_escola_ensino_medio = {
    "A": "Todo em escola pública",
    "B": "Todo em escola privada",
    "C": "Todo no exterior",
    "D": "A maior parte em escola pública",
    "E": "A maior parte em escola privada",
    "F": "Parte no Brasil e parte no exterior"
}

map_primeira_geracao = {
    "A": "Sim",
    "B": "Não"
}

map_escolaridade_pai = {
    "A": "Nenhuma",
    "B": "Ensino Fundamental: 1º ao 5º ano",
    "C": "Ensino Fundamental: 6º ao 9º ano",
    "D": "Ensino Médio",
    "E": "Ensino Superior - Graduação",
    "F": "Pós-graduação"
}

map_escolaridade_mae = {
    "A": "Nenhuma",
    "B": "Ensino Fundamental: 1º ao 5º ano",
    "C": "Ensino Fundamental: 6º ao 9º ano",
    "D": "Ensino Médio",
    "E": "Ensino Superior - Graduação",
    "F": "Pós-graduação"
}

map_motivacao_curso = {
    "A": "Inserção no mercado de trabalho",
    "B": "Influência familiar",
    "C": "Valorização profissional",
    "D": "Prestígio Social",
    "E": "Vocação",
    "F": "Oferecido na modalidade a distância",
    "G": "Baixa concorrência para ingresso",
    "H": "Outro motivo"
}

map_renda_familiar = {
    "A": "Até 1,5 salário mínimo",
    "B": "De 1,5 a 3 salários mínimos)",
    "C": "De 3 a 4,5 salários mínimos)",
    "D": "De 4,5 a 6 salários mínimos)",
    "E": "De 6 a 10 salários mínimos)",
    "F": "De 10 a 30 salários mínimos)",
    "G": "Acima de 30 salários mínimos)"
}

map_horas_trabalho = {
    "A": "Não estou trabalhando",
    "B": "Trabalho eventualmente",
    "C": "Trabalho até 20 horas semanais",
    "D": "Trabalho de 21 a 39 horas semanais",
    "E": "Trabalho 40 horas semanais ou mais"
}

map_cotas = {
    "A": "Não",
    "B": "Sim, por critério étnico-racial",
    "C": "Sim, por critério de renda",
    "D": "Sim, por ter estudado em escola pública ou particular com bolsa de estudos",
    "E": "Sim, por sistema que combina dois ou mais critérios anteriores",
    "F": "Sim, por sistema diferente dos anteriores"
}

map_avaliacao_dificuldade_fg ={
    "A": "Muito fácil",
    "B": "Fácil",
    "C": "Médio",
    "D": "Difícil",
    "E": "Muito difícil",
    "*": "Resposta anulada",
    ".": "Resposta anulada",
    " ": "Resposta anulada",
    pd.NA: "Resposta anulada"
}

    
map_avaliacao_dificuldade_ce ={
    "A": "Muito fácil",
    "B": "Fácil",
    "C": "Médio",
    "D": "Difícil",
    "E": "Muito difícil",
    "*": "Resposta anulada",
    ".": "Resposta anulada",
    " ": "Resposta anulada",
    pd.NA: "Resposta anulada"
}
df_enade['avaliacao_equipamentos'] = df_enade['avaliacao_equipamentos'].astype("Int64")

df_enade['avaliacao_ambiente'] = df_enade['avaliacao_ambiente'].astype("Int64")


map_avaliacao_equipamentos =  {
    1: "Discordo totalmente",
    2: "Discordo",
    3: "Discordo parcialmente",
    4: "Concordo parcialmente",
    5: "Concordo",
    6: "Concordo totalmente",
    7: "Não sei responder",
    8: "Não se aplica"
}

map_avaliacao_ambiente =  {
    1: "Discordo totalmente",
    2: "Discordo",
    3: "Discordo parcialmente",
    4: "Concordo parcialmente",
    5: "Concordo",
    6: "Concordo totalmente",
    7: "Não sei responder",
    8: "Não se aplica"
}


map_lists = [map_sexo, map_categoria_administrativa, map_modalidade_graduacao, map_turno_graduacao, map_cor_raca, map_tipo_escola_ensino_medio, map_primeira_geracao, map_escolaridade_pai, map_escolaridade_mae, map_motivacao_curso, map_renda_familiar, map_horas_trabalho, map_cotas, map_avaliacao_dificuldade_fg, map_avaliacao_dificuldade_ce, map_avaliacao_equipamentos, map_avaliacao_ambiente]

In [35]:
colunas_para_mapear = ["sexo", "categoria_administrativa", "modalidade_graduacao", "turno_graduacao", "cor_raca", "tipo_escola_ensino_medio", "primeira_geracao", "escolaridade_pai", "escolaridade_mae", "motivacao_curso", "renda_familiar", "horas_trabalho", "cotas", "avaliacao_dificuldade_fg", "avaliacao_dificuldade_ce", "avaliacao_equipamentos", "avaliacao_ambiente"]

In [36]:
for mapa in enumerate(map_lists):
    indice, m = mapa
    coluna = colunas_para_mapear[indice]
    df_enade[coluna] = df_enade[coluna].map(m)

In [37]:
df_enade.head(20)

,ano_enade,id_curso,categoria_administrativa,modalidade_graduacao,turno_graduacao,id_municipio,sexo,idade,cor_raca,ano_fim_ensino_medio,ano_ingresso_graduacao,tipo_escola_ensino_medio,primeira_geracao,escolaridade_pai,escolaridade_mae,motivacao_curso,renda_familiar,horas_trabalho,cotas,nota_geral,nota_formacao_geral,nota_componentes_especifico,avaliacao_dificuldade_fg,avaliacao_dificuldade_ce,avaliacao_equipamentos,avaliacao_ambiente
0,2018,2,Pública Federal,Presencial,Noturno,5103403,F,<NA>,Branca,<NA>,2014,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Médio,Médio,Discordo totalmente,Discordo totalmente
1,2018,2,Pública Federal,Presencial,Noturno,5103403,F,<NA>,Branca,<NA>,2013,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
2,2018,2,Pública Federal,Presencial,Matutino,5103403,F,<NA>,Branca,<NA>,2013,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
3,2018,2,Pública Federal,Presencial,Noturno,5103403,F,<NA>,Branca,<NA>,2014,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
4,2018,2,Pública Federal,Presencial,Noturno,5103403,F,<NA>,Branca,<NA>,2015,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
5,2018,2,Pública Federal,Presencial,Noturno,5103403,F,17,Branca,<NA>,2015,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
6,2018,2,Pública Federal,Presencial,Noturno,5103403,F,17,Branca,<NA>,2015,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
7,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2015,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
8,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2016,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo parcialmente,Discordo parcialmente
9,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2014,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
10,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2015,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
11,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2015,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo parcialmente,Discordo parcialmente
12,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2014,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
13,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2016,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
14,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2015,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
15,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2014,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
16,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2014,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
17,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2014,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
18,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2014,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente
19,2018,2,Pública Federal,Presencial,Noturno,5103403,F,18,Branca,<NA>,2014,Todo em escola pública,Sim,Nenhuma,Nenhuma,Inserção no mercado de trabalho,"Até 1,5 salário mínimo",Não estou trabalhando,Não,0.0,0.0,0.0,Resposta anulada,Resposta anulada,Discordo totalmente,Discordo totalmente

# Salvando

In [43]:
for coluna in df_enade.columns:
    print(f"{coluna}: {df_enade[coluna].isna().sum() * 100 / len(df_enade):.2f}% de nulos")

ano_enade: 0.00% de nulos
id_curso: 0.00% de nulos
categoria_administrativa: 1.24% de nulos
modalidade_graduacao: 0.00% de nulos
turno_graduacao: 0.99% de nulos
id_municipio: 0.00% de nulos
sexo: 0.03% de nulos
idade: 0.03% de nulos
cor_raca: 13.23% de nulos
ano_fim_ensino_medio: 0.05% de nulos
ano_ingresso_graduacao: 0.05% de nulos
tipo_escola_ensino_medio: 13.23% de nulos
primeira_geracao: 13.23% de nulos
escolaridade_pai: 13.23% de nulos
escolaridade_mae: 13.23% de nulos
motivacao_curso: 13.24% de nulos
renda_familiar: 13.23% de nulos
horas_trabalho: 13.23% de nulos
cotas: 13.23% de nulos
nota_geral: 20.52% de nulos
nota_formacao_geral: 20.52% de nulos
nota_componentes_especifico: 20.52% de nulos
avaliacao_dificuldade_fg: 0.00% de nulos
avaliacao_dificuldade_ce: 0.00% de nulos
avaliacao_equipamentos: 13.24% de nulos
avaliacao_ambiente: 13.24% de nulos

In [39]:
df_enade.to_csv("..\\enade_ready_to_use\\enade_limpo.csv", index=False, encoding="utf-8-sig")

In [44]:
for ano in sorted(df_enade["ano_enade"].unique()):
    df_ano = df_enade[df_enade["ano_enade"] == ano]
    df_ano.to_csv(f"..\\enade_ready_to_use\\enade_pós-processamento_{ano}.csv", index=False, encoding="utf-8-sig")

In [45]:
df_enade.columns

Index(['ano_enade', 'id_curso', 'categoria_administrativa',
       'modalidade_graduacao', 'turno_graduacao', 'id_municipio', 'sexo',
       'idade', 'cor_raca', 'ano_fim_ensino_medio', 'ano_ingresso_graduacao',
       'tipo_escola_ensino_medio', 'primeira_geracao', 'escolaridade_pai',
       'escolaridade_mae', 'motivacao_curso', 'renda_familiar',
       'horas_trabalho', 'cotas', 'nota_geral', 'nota_formacao_geral',
       'nota_componentes_especifico', 'avaliacao_dificuldade_fg',
       'avaliacao_dificuldade_ce', 'avaliacao_equipamentos',
       'avaliacao_ambiente'],
      dtype='str')